### ISSUE TITLE
The connection server failed

### ISSUE THREAD

**Issue by dong136279559** [nubomedia-vtt/nubo-test#16]
11-27 10:03:49.410 21507-21507/fi.vtt.nubotest I/MainActivity: username: drt
11-27 10:03:49.410 21507-21507/fi.vtt.nubotest I/MainActivity: roomname: 12326
11-27 10:03:49.413 21507-21507/fi.vtt.nubotest I/MainActivity: Connecting to room at wss://roomtestbed.kurento.org:8443/room
11-27 10:03:49.426 21507-21507/fi.vtt.nubotest D/ActivityThreadInjector: clearCachedDrawables.
11-27 10:03:49.526 21507-21507/fi.vtt.nubotest W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
11-27 10:03:49.531 21507-21507/fi.vtt.nubotest W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
11-27 10:03:49.647 21507-23430/fi.vtt.nubotest E/KurentoRoomAPI: onError: Connection refused
                                                                 java.net.ConnectException: Connection refused
                                                                     at sun.nio.ch.Net.connect0(Native Method)
                                                                     at sun.nio.ch.Net.connect(Net.java:477)
                                                                     at sun.nio.ch.Net.connect(Net.java:467)
                                                                     at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:669)
                                                                     at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:210)
                                                                     at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
                                                                     at java.lang.Thread.run(Thread.java:761)

**Comment by leonsaber** [comment]
did you fix this issues? I got same issues... also looking for help.
