### ISSUE TITLE
Unresolved Address Exception

### ISSUE THREAD

**Issue by daljeet33** [nubomedia-vtt/nubo-test#17]
01-03 15:44:36.116 9772-9772/fi.vtt.nubotest I/MainActivity: Connecting to room at wss://room.willab.fi:8443/room
01-03 15:44:36.132 9772-9772/fi.vtt.nubotest D/ActivityThreadInjector: clearCachedDrawables.
01-03 15:44:36.265 9772-9772/fi.vtt.nubotest W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
01-03 15:44:36.265 9772-9772/fi.vtt.nubotest W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
01-03 15:44:36.265 9772-9772/fi.vtt.nubotest W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
01-03 15:44:36.531 9772-9772/fi.vtt.nubotest I/LoginActivity: onStop
01-03 15:44:37.211 9772-9846/fi.vtt.nubotest E/KurentoRoomAPI: onError: null
                                                               java.nio.channels.UnresolvedAddressException
                                                                   at sun.nio.ch.Net.checkAddress(Net.java:134)
                                                                   at sun.nio.ch.SocketChannelImpl.connect(SocketChannelImpl.java:643)
                                                                   at org.java_websocket.client.WebSocketClient.interruptableRun(WebSocketClient.java:210)
                                                                   at org.java_websocket.client.WebSocketClient.run(WebSocketClient.java:188)
                                                                   at java.lang.Thread.run(Thread.java:760)

**Comment by kaviyarasu1987** [comment]
have you solved this issue  i have been facing the same
